### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by pysalt** [urbanchef/ugc_sprint_1#79]
Привет! Хорошая работа и код. Ниже список небольших замечаний:

1. nit: хорошо, когда [документация](https://github.com/urbanchef/ugc_sprint_1/blob/main/README.md) приложения написана на одном языке, а не кусками из двух :)
2. По одному из заданий в gitlab [actions](https://github.com/urbanchef/ugc_sprint_1/blob/main/.github/workflows/lint.yml) необходимо добавить хук с уведомлением в телеграмм. Сделайте триггер, например, на успешное прохождение пайплайна в мастере
3. Так же по одной из задач вам было необходимо выбрать хранилище для пользовательских UGC-данных (данные которые будут отдаваться пользователю, например, метка о текущем времени просмотра, но уже не в целях аналитики, а повышения UX - пользователь может продолжить просмотр с последнего места остановки). Я у вас не увидел данного исследования...Вы решили остановиться на CH для обоих кейсов (аналитика, данные юзера)
4. Можно лучше: чтобы не "проксировать" доступы между сервисами через хостовую сеть можно использовать настройку https://docs.docker.com/compose/networking/#use-a-pre-existing-network
5. [Тут](https://github.com/urbanchef/ugc_sprint_1/blob/03140735c8dc71f80d643004d7891074df61823a/log/logstash/config/logstash.conf#L31) давайте доработаем и сделаем отдельную настройку для вашего ugc-сервиса
6. Совет: в проде не забывайте менять [данную](https://github.com/urbanchef/ugc_sprint_1/blob/03140735c8dc71f80d643004d7891074df61823a/data/node1/users.xml#L12) секцию у CH

**Comment by BigDeepBlue** [comment]
@urbanchef не удивляйтесь аккаунту, забыл перелогиниться и оставил ревью с личного акка

**Comment by BigDeepBlue** [comment]
LGTM
